name: test

on:
  push:
    branches:
      - master
jobs:
    compile:
        name: Compile site assets
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: bulds
            run: |
              docker build -t nik-weter/docker-react -f Dockerfile.dev .
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run the build process with Docker
            run: |
              docker run -e CI=true nik-weter/docker-react npm run test
          - name: docker login
            uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

#          - name: Build and push
#            uses: docker/build-push-action@v3
#            with:
#              context: .
#              push: true
#              tags: nikweter/docker-react:latest

    deploy:
      name: deploy to server
      runs-on: ubuntu-latest
      steps:
          - name: Install SSH Key
            uses: shimataro/ssh-key-action@v2
            with:
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              known_hosts: unnecessary

          - name: Adding Known Hosts
            run: |
              echo $SSH_KNOWN_HOSTS >> ~/.ssh/known_hosts
              cat ~/.ssh/known_hosts
          - name: Deploy app
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.SSH_HOST }}
              username: ${{ secrets.SSH_USER }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              port: ${{ secrets.SSH_PORT }}
              script: |
                ssh root@riss.fabrika-start.ru "docker run -p 3000:3000 nikweter/docker-react:latest"
