name: test

on:
  push:
    branches:
      - master
jobs:
    compile:
        name: Compile site assets
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: bulds
            run: |
              docker build -t nik-weter/docker-react -f Dockerfile.dev .
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run the build process with Docker
            run: |
              docker run -e CI=true nik-weter/docker-react npm run test
          - name: docker login
            uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

#          - name: Build and push
#            uses: docker/build-push-action@v3
#            with:
#              context: .
#              push: true
#              tags: nikweter/docker-react:latest

    deploy:
        name: Deploy to remote server
        runs-on: ubuntu-latest
        steps:
          - name: Create SSH key
            run: |
              mkdir -p ~/.ssh/
              echo "$SSH_PRIVATE_KEY" > private.key
              sudo chmod 600 private.key
              echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
            shell: bash
            env:
              SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
              SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
              SSH_KEY_PATH: ${{ github.workspace }}/private.key

          - name: Deploy
            run: |
              ssh -i $SSH_KEY_PATH root@riss.fabrika-start.ru  "docker run -p 3000:3000 nikweter/docker-react:latest"
